### PR TITLE
Fix panic in compile_tr_private_experimental for non-expandable policies

### LINKED ISSUE #902: `compile_tr` and `compile_tr_private_experimental` fail for `pk(A)`
Both `compile_tr` and `compile_tr_private_experimental` fail for `pk(A)`. Expected result in both cases is `tr(A)`, `extract_key` correctly promotes `A` to the taproot internal key, but the remaining `Policy::Unsatisfiable` is not handled the same as `Policy::Trivial`, causing it to fall through to leaf compilation with nothing to compile.

`compile_tr_private_experimental` also panics for `and(pk(A),pk(B))` (`compile_tr` is fine there).

I discovered this while trying to push for a privacy first taproot compiler in bdk-cli: https://github.com/bitcoindevkit/bdk-cli/issues/244

### PR DESCRIPTION
**Pull request by febyeji**
Closes #902.

- Keep `pol_prob_map` in sync with `tapleaf_prob_vec` by removing entries from both data structures together. 
- Previously, removing a node from `tapleaf_prob_vec` without removing it from `pol_prob_map` caused a panic when `expand_fn` returned the same policy (e.g. for `pk(A)` or `and(pk(A),pk(B))`).
- Adds regression tests for both cases.

### CODE REVIEW

File: src/policy/concrete.rs [hunk 1]
```diff
@@ -1276,6 +1278,21 @@ mod compiler_tests {
...
     }
+
+    #[test]
+    fn compile_tr_private_non_expandable() {
+        let unspendable = "UNSPEND".to_string();
+
+        // Single key: extract_key promotes it, leaving Unsatisfiable
+        let pol = Policy::<String>::from_str("pk(A)").unwrap();
+        pol.compile_tr_private_experimental(Some(unspendable.clone()))
+            .expect("pk(A) should compile without panic");
```
Comment (va-an) [inline src/policy/concrete.rs]: I suggest adding a comparison with the expected result instead of checking for a panic as I did in #916.

Comment (febyeji) [reply src/policy/concrete.rs]: Thanks for letting me know!

**Review by apoelstra — APPROVED** [review]
ACK f728d78ceafb3abc640fccc777fecf42234b9734; successfully ran local tests
