### PR TITLE
Check for segwit standardness limits

### LINKED ISSUE #132: And()s compilation can produce invalid Script
The translation of `thresh(n, n*policy)` to a concatenation of `and()` uncovered that we can actually compile policy that are creating invalid (non-standard) Scripts.

A small test to reproduce the behaviour with a 100-of-100 multisig (which cannot be spent by a standard transaction as the number on the stack would excess the `MAX_STANDARD_P2WSH_STACK_ITEMS`).
We can create (eg) 128-of-128 p2wsh as well, which are also invalid by the witness script size.

```patch
diff --git a/src/policy/compiler.rs b/src/policy/compiler.rs
index 31ea530..28d0bec 100644
--- a/src/policy/compiler.rs
+++ b/src/policy/compiler.rs
@@ -1436,6 +1436,17 @@ mod tests {
             };
         }
     }
+
+    #[test]
+    fn test_limits() {
+        let (keys, _) = pubkeys_and_a_sig(100);
+
+        let pubkeys: Vec<Concrete<bitcoin::PublicKey>> =
+            keys.iter().map(|pubkey| Concrete::Key(*pubkey)).collect();
+        let big_thresh_ms: Result<SegwitMiniScript, _> =
+            Concrete::Threshold(100, pubkeys).compile();
+        assert_eq!(big_thresh_ms, Err(CompilerError::MaxOpCountExceeded));
+    }
 }
 
 #[cfg(all(test, feature = "unstable"))]
```

### PR DESCRIPTION
**Pull request by darosior**
This is the first part of #148, in order to fix #132.

This comports:
- a few drive-by cleanup commits added as i was reading the cost computation internals
- an API break: change max_witness_elements() to return an Option instead of unwrap()ing internally
- an addition of bounds-check for segwit standardness rules under the Segwitv0 context
- a move of the OPs count check to context in order to also check it at parse time (not only compilation) 

The second part is -coming soon :tm: and- storing  the cost in witness elements in the ExtraData struct in order to avoid the suboptimal recursion at each check.

### CODE REVIEW

File: src/miniscript/astelem.rs [hunk 1]
```diff
@@ -848,70 +848,79 @@ impl<Pk: MiniscriptKey, Ctx: ScriptContext> Terminal<Pk, Ctx> {
...
+            Terminal::After(..) | Terminal::Older(..) => Some(0),
             Terminal::Sha256(..)
             | Terminal::Hash256(..)
             | Terminal::Ripemd160(..)
-            | Terminal::Hash160(..) => 1,
-            Terminal::True => 0,
-            Terminal::False => 0,
+            | Terminal::Hash160(..) => Some(1),
+            Terminal::True => Some(0),
+            Terminal::False => Some(0),
```
Comment (sanket1729) [inline src/miniscript/astelem.rs:861]: This was a bug in previous code too. I think this should be None.

Comment (darosior) [reply src/miniscript/astelem.rs:861]: Yeah definitely, it is in my "track costs" branch and in Sipa's implementation.

**Comment by darosior** [comment]
I still need to add some tests. Some manual testing uncovered a panic on Descriptor's `max_witness_elements()`.

**Comment by darosior** [comment]
Amended to make `Descriptor`'s `max_satisfaction_weight` return an Option as well as mentionned by @sanket1729 [here](https://github.com/rust-bitcoin/rust-miniscript/pull/150#discussion_r502440813). It makes sense as we can't really know if we are given a valid Miniscript.

**Comment by sanket1729** [comment]
@darosior, the typechecking rules for and_or would make sure to accept only fragments such that the first part is dissatifiable. I don't know if the above comment is resolved and I am not able to follow the exact question there.

**Comment by darosior** [comment]
> I don't know if the above comment is resolved and I am not able to follow the exact question there.

Looks like you just answered it. Thanks. This is now ready for review.

File: src/miniscript/context.rs [hunk 2]
```diff
@@ -111,12 +134,31 @@ impl ScriptContext for Segwitv0 {
...
+                    return Err(ScriptContextError::CompressedOnly);
+                }
+
+                Ok(())
             }
             _ => Ok(()),
         }
     }
+
+    fn check_ms_validity<Pk: MiniscriptKey, Ctx: ScriptContext>(
```
Comment (sanket1729) [inline src/miniscript/context.rs:172]: As discussed in #148, we should combine check_ms_validity and check_frag_validity

File: src/miniscript/context.rs [hunk 3]
```diff
@@ -53,6 +56,11 @@ impl fmt::Display for ScriptContextError {
                 "At least one spending path in the Miniscript fragment has more \
                  witness items than MAX_STANDARD_P2WSH_STACK_ITEMS.",
             ),
+            ScriptContextError::MaxOpCountExceeded => write!(
+                f,
+                "At least one satisfaction path in the Miniscript fragment contains \
+                 more than `MAX_OPS_PER_SCRIPT`(201) opcodes."
```
Comment (sanket1729) [inline src/miniscript/context.rs:67]: nit: use variable MAX_OPS_PER_SCRIPT variable in format string instead of hardcoded 201.

Comment (sanket1729) [reply src/miniscript/context.rs:67]: Or you can remove 201 completely. Anything works

**Review by sanket1729 — COMMENTED** [review]
I think this is almost good to go. Left some minor feedback

File: src/miniscript/context.rs (hunk 2 above)
Comment (darosior) [reply src/miniscript/context.rs:172]: Just implemented it and moving `check_frag_validity` to take a Miniscript reduces the number of call sites. Eg we cannot call it anymore in https://github.com/rust-bitcoin/rust-miniscript/blob/b70042e5b29b077ad123b1af5f855a02d8a4b0f9/src/miniscript/astelem.rs#L63-L75

Comment (darosior) [reply src/miniscript/context.rs:172]: Actually, for all Terminal-only methods. That's the reason why i added another method in the first place: check_frag is really Terminal-only while check_ms is Miniscript-only.
At very first (#148), i combined both into check_frag and took a Terminal: it was *really* dirty.

File: src/miniscript/context.rs (hunk 3 above)
Comment (darosior) [reply src/miniscript/context.rs:67]: I don't expect this value to change much anyways :p
That said, removed it and the backticks from the error message as it makes it easier to match errors against it.

**Comment by darosior** [comment]
Fixed the error messages.

File: src/miniscript/context.rs (hunk 2 above)
Comment (sanket1729) [reply src/miniscript/context.rs:172]: There is a cheap function to get Miniscript from terminals. `Miniscript::from_ast`. 
I made a commit on top of this PR that combines the checks:
https://github.com/sanket1729/rust-miniscript/commit/4311108698c3590d0f587391be5f5eee8e5e5cee

Comment (darosior) [reply src/miniscript/context.rs:172]: Thanks!

**Comment by darosior** [comment]
Cherry-picked @sanket1729 commit on top of this.

**Comment by sanket1729** [comment]
@darosior, looks like I did not test my commit with compiler feature and forgot to update `compiler.rs` that is causing the test failures. Can you fix the commit to remove the `Ctx::check_frag..` from `compiler.rs`?

**Comment by darosior** [comment]
Amended..

**Review by sanket1729 — APPROVED** [review]
tAck e2baa3c9b484d0168eb1d7310c8d5474f892126a

File: src/miniscript/types/extra_props.rs [hunk 4]
```diff
@@ -93,9 +93,8 @@ impl TimeLockInfo {
     }
 }
 
-/// Structure representing the extra type properties of a fragment which are
-/// relevant to legacy(pre-segwit) safety and fee estimation. If a fragment is
-/// used in pre-segwit transactions it will only be malleable but still is
+/// Structure representing the extra type properties of a fragment. If a fragment
+/// is used in pre-segwit transactions it will only be malleable but still is
```
Comment (apoelstra) [inline src/miniscript/types/extra_props.rs:102]: I think we should delete the second sentence. I can't see how it's related to this structure.

File: src/miniscript/mod.rs [hunk 5]
```diff
@@ -186,8 +186,8 @@ impl<Pk: MiniscriptKey, Ctx: ScriptContext> Miniscript<Pk, Ctx> {
     /// This function may panic on misformed `Miniscript` objects which do
     /// not correspond to semantically sane Scripts. (Such scripts should be
     /// rejected at parse time. Any exceptions are bugs.)
```
Comment (apoelstra) [inline src/miniscript/mod.rs:188]: We should fix the comment now that this doesn't panic

File: src/miniscript/context.rs [hunk 6]
```diff
@@ -111,12 +134,31 @@ impl ScriptContext for Segwitv0 {
         frag: &Terminal<Pk, Ctx>,
```
Comment (apoelstra) [inline src/miniscript/context.rs]: If this is only checking a terminal, the function name should have `terminal` rather than `frag` in it.

File: src/miniscript/context.rs (hunk 2 above)
Comment (apoelstra) [inline src/miniscript/context.rs:142]: ...and this one should be named `check_frag_validity`

Comment (apoelstra) [reply src/miniscript/context.rs:142]: I wonder if the sanity checks in `from_ast` should be moved into `check_frag_validity`, and then `from_ast` can be replaced by an `impl From<Terminal> for Miniscript`

**Comment by apoelstra** [comment]
ack e2baa3c9b484d0168eb1d7310c8d5474f892126a

We can fix comments/renames in a followup PR

**Comment by apoelstra** [comment]
Not sure what's up with CI here

**Comment by apoelstra** [comment]
Ah, it's because the PR is based on `master` prior to us updating the github actions.

I'll go ahead and merge this, since it passed the 1.22.0 check, so clearly it must've passed the 1.29.0 one.

**Comment by darosior** [comment]
> ack e2baa3c
> We can fix comments/renames in a followup PR

Will do a follow-up, or add it at part of  #150

File: src/miniscript/decode.rs [hunk 7]
```diff
@@ -173,6 +173,7 @@ impl<Pk: MiniscriptKey, Ctx: ScriptContext> TerminalStack<Pk, Ctx> {
         F: FnOnce(Arc<Miniscript<Pk, Ctx>>) -> Terminal<Pk, Ctx>,
     {
         let top = self.pop().unwrap();
+        Ctx::check_ms_validity(&top)?;
```
Comment (apoelstra) [inline src/miniscript/decode.rs]: Oops! It turns out that this can panic if we call it on malformed input, because it tries to count the max_dissatisfaction_witness_elements but we still have a panic there https://github.com/rust-bitcoin/rust-miniscript/blob/master/src/miniscript/astelem.rs#L774

This caused a fuzztest failure on another PR.
